/**
 * Auth.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Класс для отправки токенов
 */
export interface AuthResponseDto { 
    /**
     * Access токен
     */
    accessToken: string | null;
    /**
     * Refresh токен
     */
    refreshToken: string | null;
}

