/**
 * Auth.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Класс аутентификации пользователя
 */
export interface LoginRequestDto { 
    /**
     * Имя пользователя
     */
    emailAuth: string | null;
    /**
     * Пароль
     */
    password: string | null;
}

