/**
 * Auth.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Класс для refresh токена
 */
export interface RefreshRequestDto { 
    /**
     * Refresh токен
     */
    refreshToken: string | null;
}

