/**
 * Auth.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterRequestDto { 
    /**
     * Email для регистрации
     */
    authEmail: string | null;
    /**
     * пассворд
     */
    password: string | null;
    /**
     * Повторный пароль
     */
    repeatPassword: string | null;
    /**
     * Роль
     */
    role: string | null;
}

