/**
 * Donutsbox.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AddVideosResponseDto { 
    postId?: string;
    videosAdded?: number;
    totalVideos?: number;
    message?: string | null;
}

