/**
 * Donutsbox.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubscriptionDto } from './subscriptionDto';


export interface AuthorRequestDto { 
    /**
     * Идентификатор страницы автора
     */
    id: string;
    /**
     * Название страницы автора
     */
    pageName: string | null;
    /**
     * Ссылка на аватарку автора
     */
    avatarUrl?: string | null;
    /**
     * Описание страницы автора
     */
    description?: string | null;
    /**
     * Количество подписчиков
     */
    subscribersCount: number;
    /**
     * Подписки
     */
    subscriptions: Array<SubscriptionDto> | null;
}

