/**
 * Donutsbox.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthorPreviewDto { 
    /**
     * Идентификатор автора
     */
    id?: string;
    /**
     * Ник автора/страницы
     */
    pageName?: string | null;
    /**
     * Ссылка на аватар автора
     */
    avatarUrl?: string | null;
}

