/**
 * Donutsbox.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ContentPostDto { 
    /**
     * Идентификатор поста
     */
    postId: string;
    /**
     * Идентификатор страницы автора
     */
    pageId: string;
    /**
     * Заголовок поста
     */
    title?: string | null;
    /**
     * Текст поста
     */
    text?: string | null;
    /**
     * Дата создания поста
     */
    createdAt: string;
    /**
     * Кол-во дизлайков
     */
    dislikesCount: number;
    /**
     * Ссылки на аудио
     */
    audioURLs: Array<string> | null;
    /**
     * Ссылки на видео
     */
    videoURLs: Array<string> | null;
    /**
     * Ссылки на картинки
     */
    pictureURLs: Array<string> | null;
}

