/**
 * Donutsbox.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateDraftRequestDto { 
    title?: string | null;
    text?: string | null;
    pictureUrls?: Array<string> | null;
    audioUrls?: Array<string> | null;
}

