/**
 * Donutsbox.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PostDetailsDto } from './postDetailsDto';
import { CreatorInfoDto } from './creatorInfoDto';


export interface CreatorPostsResponseDto { 
    creator?: CreatorInfoDto;
    total?: number;
    page?: number;
    pageSize?: number;
    posts?: Array<PostDetailsDto> | null;
}

