/**
 * Donutsbox.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreatorPageDataDto { 
    /**
     * Название страницы автора
     */
    pageName: string | null;
    /**
     * Ссылка на аватарку автора
     */
    avatarUrl?: string | null;
    /**
     * Ссылка на баннер автора
     */
    bannerUrl?: string | null;
    /**
     * Описание страницы автора
     */
    description?: string | null;
    /**
     * Количество подписчиков
     */
    subscribersCount: number;
}

