/**
 * Donutsbox.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreatorInfoDto { 
    id?: string;
    name?: string | null;
    pageName?: string | null;
    avatarUrl?: string | null;
    description?: string | null;
    subscribersCount?: number;
}

