/**
 * Donutsbox.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * DTO для создания комментария
 */
export interface CreatePostCommentDto { 
    /**
     * Идентификатор поста
     */
    postId: string;
    /**
     * Текст комментария
     */
    text: string;
}

