/**
 * Donutsbox.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * DTO для заполнения данных при первом входе
 */
export interface FirstLoginDto { 
    /**
     * Имя пользователя
     */
    name: string | null;
    /**
     * Номер телефона
     */
    phoneNumber?: string | null;
}

