/**
 * Donutsbox.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VideoDto } from './videoDto';


export interface MyVideoResponseDto { 
    total?: number;
    page?: number;
    pageSize?: number;
    videos?: Array<VideoDto> | null;
}

