/**
 * Donutsbox.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PostVideoDto } from './postVideoDto';


export interface PostDetailsDto { 
    id?: string;
    title?: string | null;
    text?: string | null;
    createdAt?: string;
    isPublished?: boolean;
    likesCount?: number;
    dislikesCount?: number;
    commentsCount?: number;
    videos?: Array<PostVideoDto> | null;
    pictureUrls?: Array<string> | null;
    creatorPageName?: string | null;
    creatorId?: string | null;
    creatorAvatarUrl?: string | null;
    reactionTypeId?: number;
}

