/**
 * Donutsbox.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PostDraftResponseDto { 
    postId?: string;
    title?: string | null;
    isPublished?: boolean;
    isPublic?: boolean;
    allowedSubscriptionIds?: Array<string> | null;
    message?: string | null;
}

