/**
 * Donutsbox.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * DTO комментария к посту
 */
export interface PostCommentDto { 
    /**
     * Идентификатор комментария
     */
    id: string;
    /**
     * Идентификатор поста
     */
    postId: string;
    /**
     * Идентификатор пользователя
     */
    userId: string;
    /**
     * Имя пользователя
     */
    userName?: string | null;
    /**
     * URL аватарки пользователя
     */
    userAvatarUrl?: string | null;
    /**
     * Текст комментария
     */
    text: string | null;
    /**
     * Дата создания комментария
     */
    createdAt: string;
}

