/**
 * Donutsbox.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PublishPostResponseDto { 
    postId?: string;
    isPublished?: boolean;
    publishedAt?: string;
    message?: string | null;
}

