/**
 * Donutsbox.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SessionInfoDto { 
    userId?: string;
    displayName?: string | null;
    email?: string | null;
    role?: string | null;
    isCreator?: boolean;
    hasCreatorPage?: boolean;
    creatorPageId?: string | null;
}

