/**
 * Donutsbox.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SubscriptionUpdateDto { 
    /**
     * Название подписки
     */
    name: string | null;
    /**
     * Описание подписки
     */
    description: string | null;
    /**
     * Цена подписки (месячная)
     */
    price: string | null;
}

