/**
 * Donutsbox.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SubscriptionPaymentRequestDto { 
    /**
     * Идентификатор подписки (тарифа), который покупает пользователь.
     */
    subscriptionId: string;
    /**
     * URL, на который YooKassa вернёт пользователя после оплаты.  Если не указан, будет использовано значение из конфигурации.
     */
    returnUrl?: string | null;
}

