/**
 * Donutsbox.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SubscriptionDto { 
    /**
     * Идентификатор
     */
    id: string;
    /**
     * Цена подписки
     */
    price: string | null;
    /**
     * Название подписки
     */
    name: string | null;
    /**
     * Описание подписки
     */
    description: string | null;
    /**
     * Ссылка на картинку подписки
     */
    pictureURL?: string | null;
    /**
     * Идентификатор периода подписки
     */
    subscriptionPeriodId: number;
    /**
     * Количество месяцев в периоде
     */
    subscriptionPeriodMonths: number;
    /**
     * Цена в расчете за месяц
     */
    monthlyPrice: string | null;
    /**
     * Родительская подписка
     */
    parentSubscriptionId?: string | null;
}

