/**
 * Donutsbox.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SubscriptionPaymentStatusDto { 
    /**
     * Идентификатор заявки на оплату в нашей системе.
     */
    paymentRequestId: string;
    /**
     * Идентификатор платежа в YooKassa, если он получен.
     */
    paymentId?: string | null;
    /**
     * Текущий статус платежа (pending, waiting_for_capture, succeeded, canceled и т.д.).
     */
    status: string | null;
    /**
     * Статус подписки после обработки платежа.
     */
    subscriptionStatus?: string | null;
    /**
     * Дата, до которой активна подписка (если подписка активна).
     */
    subscriptionEndDate?: string | null;
    /**
     * Истекает ли ссылка на оплату и когда.
     */
    expiresAt?: string | null;
    /**
     * Ссылка на подтверждение оплаты (если платеж ещё не завершен).
     */
    confirmationUrl?: string | null;
}

