/**
 * Donutsbox.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdatePostAccessRequestDto { 
    /**
     * Сделать пост публичным для всех пользователей
     */
    isPublic?: boolean;
    /**
     * Разрешенные уровни подписок (используются, если IsPublic == false).  Пустой список означает доступ для всех активных подписчиков создателя.
     */
    allowedSubscriptionIds?: Array<string> | null;
}

