/**
 * Donutsbox.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Информация о пользователе
 */
export interface UserRequestDto { 
    /**
     * Id
     */
    id: string;
    /**
     * Имя пользователя
     */
    userName: string | null;
}

