/**
 * Donutsbox.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserAuthDto { 
    /**
     * Id
     */
    id: string;
    /**
     * Email для аунтентификации
     */
    authEmail: string | null;
    /**
     * пассворд
     */
    password: string | null;
    /**
     * Дата последнего входа
     */
    lastAuth: string;
}

