/**
 * Donutsbox.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserDataDto { 
    /**
     * Идентификатор
     */
    id: string;
    /**
     * Id непоссредственного пользователя
     */
    userId: string;
    /**
     * Ссылка на хранилище аватарки
     */
    avatarUrl: string | null;
    /**
     * Раздел \"о себе\" пользователя
     */
    description?: string | null;
    /**
     * Email для уведомлений
     */
    notificationEmail?: string | null;
    /**
     * Номер телефона
     */
    phoneNumber?: string | null;
    /**
     * TBD
     */
    paymentInfo?: string | null;
}

