/**
 * Donutsbox.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserDto { 
    /**
     * Идентификатор
     */
    guid: string;
    /**
     * Имя пользователя
     */
    name: string | null;
    /**
     * Тип пользователя
     */
    typeId: number;
    /**
     * Сущность для авторизации
     */
    authId: string | null;
}

