/**
 * Donutsbox.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserSubscriptionDto { 
    /**
     * Идентификатор
     */
    id: string;
    /**
     * Идентификатор пользователя, который подписан
     */
    userId: string;
    /**
     * Идентификатор подписки (тип подписки)
     */
    subscriptionId: string;
    /**
     * Дата начала подписки
     */
    beginDate: string;
    /**
     * Дата конца подписки
     */
    endDate: string;
    /**
     * Статус подписки
     */
    status: string | null;
    /**
     * Идентификатор платежа, активировавшего подписку
     */
    paymentId?: string | null;
    /**
     * Дата создания записи подписки
     */
    createdAt: string;
    /**
     * Дата последнего обновления записи подписки
     */
    updatedAt: string;
}

