/**
 * Donutsbox.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VideoDto { 
    id?: string;
    title?: string | null;
    status?: string | null;
    createdAt?: string;
    thumbnailUrl?: string | null;
    processedPath?: string | null;
    contentPostId?: string | null;
    hlsUrl?: string | null;
}

