/**
 * Donutsbox.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { YooKassaConfirmationResponse } from './yooKassaConfirmationResponse';
import { YooKassaAmount } from './yooKassaAmount';


export interface YooKassaPaymentResponse { 
    id: string | null;
    status: string | null;
    paid?: boolean;
    amount: YooKassaAmount;
    created_at?: string | null;
    expires_at?: string | null;
    confirmation?: YooKassaConfirmationResponse;
    metadata?: { [key: string]: string; } | null;
}

