/**
 * Admin.Service.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * DTO для отображения пользователя в админ-панели
 */
export interface AdminUserListDto { 
    id?: string;
    name?: string | null;
    email?: string | null;
    userType?: string | null;
    createdAt?: string;
    hasCreatorPage?: boolean;
    postsCount?: number;
    subscriptionsCount?: number;
}

