/**
 * Admin.Service.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdminAuthorListDto { 
    id?: string;
    creatorPageId?: string;
    name?: string | null;
    email?: string | null;
    userType?: string | null;
    createdAt?: string;
    postsCount?: number;
    subscriptionsCount?: number;
    subscribersCount?: number;
    isShadowBanned?: boolean;
}

