/**
 * Admin.Service.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * DTO для результата удаления
 */
export interface AdminDeleteResultDto { 
    success?: boolean;
    message?: string | null;
    deletedEntities?: Array<string> | null;
    warnings?: Array<string> | null;
}

