/**
 * Admin.Service.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * DTO для ответа на действия администратора
 */
export interface AdminActionResponseDto { 
    /**
     * Успешность операции
     */
    success?: boolean;
    /**
     * Сообщение о результате операции
     */
    message?: string | null;
}

