/**
 * Admin.Service.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * DTO для отображения поста в админ-панели
 */
export interface AdminContentPostListDto { 
    id?: string;
    title?: string | null;
    text?: string | null;
    creatorPageDataId?: string;
    creatorName?: string | null;
    isPublished?: boolean;
    createdAt?: string | null;
    likesCount?: number;
    dislikesCount?: number;
    commentsCount?: number;
    mediaCount?: number;
    isShadowBanned?: boolean;
}

